def register_reset(func) -> None: ...
def _reset() -> None: ...

# Names in __all__ with no definition:
#   CMapSearchPath
#   T1SearchPath
#   TTFSearchPath
#   _FUZZ
#   __builtins__
#   allowShortTableRows
#   allowTTFSubsetting
#   allowTableBoundsErrors
#   autoConvertEncoding
#   autoGenerateMissingTTFName
#   canvas_baseColor
#   canvas_basefontname
#   debug
#   decimalSymbol
#   defaultEncoding
#   defaultGraphicsFontName
#   defaultImageCaching
#   defaultPageSize
#   documentLang
#   embeddedHyphenation
#   emptyTableAction
#   encryptionStrength
#   eps_preview
#   eps_preview_transparent
#   eps_ttf_embed
#   eps_ttf_embed_uid
#   errorOnDuplicatePageLabelPage
#   fsEncodings
#   hyphenationLang
#   hyphenationMinWordLength
#   ignoreContainerActions
#   imageReaderFlags
#   invariant
#   listWrapOnFakeWidth
#   longTableOptimize
#   odbc_driver
#   overlapAttachedSpace
#   pageCompression
#   paraFontSizeHeightOffset
#   pdfComments
#   pdfMultiLine
#   platypus_link_underline
#   renderPMBackend
#   reserveTTFNotdef
#   rtlSupport
#   shapeChecking
#   showBoundary
#   spaceShrinkage
#   strikeGap
#   strikeOffset
#   strikeWidth
#   trustedHosts
#   trustedSchemes
#   ttfAsciiReadable
#   underlineGap
#   underlineOffset
#   underlineWidth
#   uriWasteReduce
#   useA85
#   verbose
#   warnOnMissingFontGlyphs
#   wrapA85
