from typing import Any

allowTableBoundsErrors: int
shapeChecking: int
defaultEncoding: str
defaultGraphicsFontName: str
pageCompression: int
useA85: int
defaultPageSize: str
defaultImageCaching: int
warnOnMissingFontGlyphs: int
verbose: int
showBoundary: int
emptyTableAction: str
invariant: int
eps_preview_transparent: Any
eps_preview: int
eps_ttf_embed: int
eps_ttf_embed_uid: int
overlapAttachedSpace: int
longTableOptimize: int
autoConvertEncoding: int
_FUZZ: float
wrapA85: int
fsEncodings: Any
odbc_driver: str
platypus_link_underline: int
canvas_basefontname: str
allowShortTableRows: int
imageReaderFlags: int
paraFontSizeHeightOffset: int
canvas_baseColor: Any
ignoreContainerActions: int
ttfAsciiReadable: int
pdfMultiLine: int
pdfComments: int
debug: int
rtlSupport: int
listWrapOnFakeWidth: int
underlineWidth: str
underlineOffset: str
underlineGap: str
strikeWidth: str
strikeOffset: str
strikeGap: str
decimalSymbol: str
errorOnDuplicatePageLabelPage: int
autoGenerateMissingTTFName: int
allowTTFSubsetting: Any
spaceShrinkage: float
hyphenationLang: str
uriWasteReduce: int
embeddedHyphenation: int
hyphenationMinWordLength: int
reserveTTFNotdef: int
documentLang: Any
encryptionStrength: int
trustedHosts: Any
trustedSchemes: Any
renderPMBackend: str
T1SearchPath: Any
TTFSearchPath: Any
CMapSearchPath: Any
