from typing import Any

_libart_version: str
_version: str

def delCache() -> Any: ...
def ft_get_face(fontName) -> ft_faceinstance: ...
def gstate(*args, **kwargs) -> Any: ...
def makeT1Font(fontName, pfbPath, names) -> Any: ...
def parse_utf8(utf8_string) -> Any: ...
def pil2pict(cols, rows, datastr, palette) -> Any: ...
