from typing import Any

from reportlab.lib.rl_accel import fp_str as fp_str
from reportlab.pdfgen import pdfgeom as pdfgeom

__version__: str
__doc__: str

class PDFPathObject:
    _code: Any
    _code_append: Any
    def __init__(self, code: Any | None = ...) -> None: ...
    def _init_code_append(self, c) -> None: ...
    def getCode(self): ...
    def moveTo(self, x, y) -> None: ...
    def lineTo(self, x, y) -> None: ...
    def curveTo(self, x1, y1, x2, y2, x3, y3) -> None: ...
    def arc(self, x1, y1, x2, y2, startAng: int = ..., extent: int = ...) -> None: ...
    def arcTo(self, x1, y1, x2, y2, startAng: int = ..., extent: int = ...) -> None: ...
    def rect(self, x, y, width, height) -> None: ...
    def ellipse(self, x, y, width, height) -> None: ...
    def _curves(self, curves, initial: str = ...) -> None: ...
    def circle(self, x_cen, y_cen, r) -> None: ...
    def roundRect(self, x, y, width, height, radius) -> None: ...
    def close(self) -> None: ...
