from typing import Any, ClassVar

version: str

class BoxList(list):
    state: ClassVar[getset_descriptor] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def classmeth(cls, *args, **kw) -> Any: ...
    def getstate(self) -> state: ...
    def setstate(self, state) -> Any: ...
    def staticmeth(self, *args, **kwargs) -> Any: ...

def Box(width, character=...) -> Any: ...
def Glue(width, stretch, shrink) -> Any: ...
def Penalty(width, penalty, flagged=...) -> Any: ...
def add32(x, y) -> Any: ...
def asciiBase85Decode(*args, **kwargs) -> Any: ...
def asciiBase85Encode(*args, **kwargs) -> Any: ...
def calcChecksum(string) -> Any: ...
def escapePDF(s) -> Any: ...
def fp_str(*args, **kwargs) -> Any: ...
def hex32(*args, **kwargs) -> Any: ...
def instanceStringWidthT1(*args, **kwargs) -> Any: ...
def instanceStringWidthTTF(*args, **kwargs) -> Any: ...
def sameFrag(f, g) -> Any: ...
def unicode2T1(*args, **kwargs) -> Any: ...
