from typing import Any

class ArcIV:
    _key: Any
    def __init__(self, key) -> None: ...
    def reset(self) -> None: ...
    _i: Any
    _j: Any
    def _encode(self, B): ...
    def encode(self, S): ...

def encode(text, key): ...
def decode(text, key): ...
