__version__: str
__doc__: str

def rectCorner(x, y, width, height, anchor: str = ..., dims: bool = ...): ...
def aspectRatioFix(
    preserve, anchor, x, y, width, height, imWidth, imHeight, anchorAtXY: bool = ...
): ...
