from typing import Any

from .utils import isStr as isStr

__version__: str
__doc__: str
_bigBangScalar: int
_bigCrunchScalar: int
_daysInMonthNormal: Any
_daysInMonthLeapYear: Any
_dayOfWeekName: str
_dayOfWeekNameLower: Any
_monthName: str
_monthNameLower: Any
_DateSeqTypes: Any
_fmtPat: Any
_iso_re: Any

def getStdMonthNames(): ...
def getStdShortMonthNames(): ...
def getStdDayNames(): ...
def getStdShortDayNames(): ...
def isLeapYear(year): ...

class NormalDateException(Exception): ...

class NormalDate:
    def __init__(self, normalDate: Any | None = ...) -> None: ...
    def add(self, days) -> None: ...
    def __add__(self, days): ...
    def __radd__(self, days): ...
    def clone(self): ...
    def __lt__(self, other): ...
    def __le__(self, other): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
    def __ge__(self, other): ...
    def __gt__(self, other): ...
    def day(self): ...
    def dayOfWeek(self): ...
    @property
    def __day_of_week_name__(self): ...
    def dayOfWeekAbbrev(self): ...
    def dayOfWeekName(self): ...
    def dayOfYear(self): ...
    def daysBetweenDates(self, normalDate): ...
    def equals(self, target): ...
    def endOfMonth(self): ...
    def firstDayOfMonth(self): ...
    def formatUS(self): ...
    def formatUSCentury(self): ...
    def _fmtM(self): ...
    def _fmtMM(self): ...
    def _fmtMMM(self): ...
    def _fmtMMMM(self): ...
    def _fmtMMMMM(self): ...
    def _fmtD(self): ...
    def _fmtDD(self): ...
    def _fmtDDD(self): ...
    def _fmtDDDD(self): ...
    def _fmtYY(self): ...
    def _fmtYYYY(self): ...
    def formatMS(self, fmt): ...
    def __getstate__(self): ...
    def __hash__(self): ...
    def __int__(self): ...
    def isLeapYear(self): ...
    def _isValidNormalDate(self, normalDate): ...
    def lastDayOfMonth(self): ...
    def localeFormat(self): ...
    def month(self): ...
    @property
    def __month_name__(self): ...
    def monthAbbrev(self): ...
    def monthName(self): ...
    def normalize(self, scalar) -> None: ...
    def range(self, days): ...
    def __repr__(self): ...
    def scalar(self): ...
    def setDay(self, day) -> None: ...
    def setMonth(self, month) -> None: ...
    normalDate: Any
    def setNormalDate(self, normalDate) -> None: ...
    def setYear(self, year) -> None: ...
    __setstate__: Any
    def __sub__(self, v): ...
    def __rsub__(self, v): ...
    def toTuple(self): ...
    def year(self): ...

def bigBang(): ...
def bigCrunch(): ...
def dayOfWeek(y, m, d): ...
def firstDayOfYear(year): ...
def FND(d): ...

Epoch: Any
AND = NormalDate
BDEpoch: Any
BDEpochScalar: int

class BusinessDate(NormalDate):
    def add(self, days) -> None: ...
    def __add__(self, days): ...
    def __sub__(self, v): ...
    def asNormalDate(self): ...
    def daysBetweenDates(self, normalDate): ...
    def _checkDOW(self) -> None: ...
    def normalize(self, i) -> None: ...
    def scalar(self): ...
    def setNormalDate(self, normalDate) -> None: ...
