from typing import Any

class PropertySet:
    defaults: Any
    name: Any
    parent: Any
    def __init__(self, name, parent: Any | None = ..., **kw) -> None: ...
    def _setKwds(self, **kw) -> None: ...
    def __repr__(self): ...
    def refresh(self) -> None: ...
    def listAttrs(self, indent: str = ...) -> None: ...
    def clone(self, name, parent: Any | None = ..., **kwds): ...

class ParagraphStyle(PropertySet):
    defaults: Any

class LineStyle(PropertySet):
    defaults: Any
    def prepareCanvas(self, canvas) -> None: ...

class ListStyle(PropertySet):
    defaults: Any

class StyleSheet1:
    byName: Any
    byAlias: Any
    def __init__(self) -> None: ...
    def __getitem__(self, key): ...
    def get(self, key, default=...): ...
    def __contains__(self, key): ...
    def has_key(self, key): ...
    def add(self, style, alias: Any | None = ...) -> None: ...
    def list(self) -> None: ...

def getSampleStyleSheet(): ...
