from reportlab.graphics.shapes import Circle as Circle
from reportlab.graphics.shapes import Polygon as Polygon
from reportlab.graphics.shapes import Rect as Rect
from reportlab.graphics.widgets.signsandsymbols import SmileyFace as SmileyFace
from reportlab.lib import colors as colors

__version__: str
__doc__: str

def makeEmptySquare(x, y, size, color): ...
def makeFilledSquare(x, y, size, color): ...
def makeFilledDiamond(x, y, size, color): ...
def makeEmptyCircle(x, y, size, color): ...
def makeFilledCircle(x, y, size, color): ...
def makeSmiley(x, y, size, color): ...
